org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

server_software_name=haxiCore
description=Fork of Poseidon providing Bukkit #1060 to older Beta versions (b1.0-b1.7.3) 
version=2.0.2

homepageUrl=
issueUrl=https://github.com/moresteck/uberbukkit/issues
sourceUrl=https://github.com/moresteck/uberbukkit

java_version=8