#Minecraft server properties
#Mon Dec 15 08:36:45 EST 2025
level-name=world
allow-nether=true
view-distance=10
spawn-monsters=true
online-mode=false
gamemode=hardcore
spawn-animals=true
pvp=true
server-ip=
max-players=20
voice-chat=true
voice-rate-max-packets-per-sec=120
voice-rate-max-bytes-per-sec=131072
voice-rate-burst-seconds=2
voice-require-udp-bind=false
level-seed=
server-port=25565
allow-flight=false
level-type=DEFAULT
white-list=false
motd=A Minecraft Server
