#Server Threading Configuration
#WARNING: Async features are experimental!
#Async chunk generation is generally safe.
#Async lighting and entity processing may cause issues.
#Sun Mar 22 20:08:57 MSK 2026
async.chunk-generation.enabled=true
async.chunk-generation.threads=2
async.entity-processing.enabled=false
async.entity-processing.threads=2
async.lighting.enabled=false
async.lighting.threads=2
chunk-compression.high-watermark-percent=85
chunk-compression.low-watermark-percent=50
chunk-compression.queue-capacity=10240
chunk-compression.threads=2
threading.max-tasks-per-tick=100
